# Generated by Django 4.0.1 on 2022-01-27 10:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(default='Codin India', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hackerrank_PS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Python_For_Beginners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
