# Generated by Django 4.0.1 on 2022-01-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Python_For_Beginners',
            new_name='Playlist',
        ),
        migrations.DeleteModel(
            name='Hackerrank_PS',
        ),
    ]
