# Generated by Django 4.0.1 on 2022-01-27 14:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCodes', '0003_codes_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackerrankProblemSolving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(default='Codin India', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PythonForBegginers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(default='Codin India', max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Codes',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
