# Generated by Django 4.0.1 on 2022-02-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCodes', '0005_webdesign_alter_hackerrankproblemsolving_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='hackerrankproblemsolving',
            name='proj',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pythonforbegginers',
            name='proj',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webdesign',
            name='proj',
            field=models.BooleanField(default=False),
        ),
    ]
