# Generated by Django 4.0.1 on 2022-02-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyCodes', '0007_rename_category_hackerrankproblemsolving_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerrankproblemsolving',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyCodes.category'),
        ),
        migrations.AlterField(
            model_name='pythonforbegginers',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyCodes.category'),
        ),
        migrations.AlterField(
            model_name='webdesign',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyCodes.category'),
        ),
    ]
