# Generated by Django 4.0.1 on 2022-02-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCodes', '0008_alter_hackerrankproblemsolving_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
