# Generated by Django 4.0.1 on 2022-02-17 07:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyCodes', '0009_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('proj', models.BooleanField(default=False)),
                ('author', models.CharField(default='Coding India', max_length=150)),
                ('HTML', ckeditor.fields.RichTextField(blank=True)),
                ('Css', ckeditor.fields.RichTextField(blank=True)),
                ('Js', ckeditor.fields.RichTextField(blank=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyCodes.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='pythonforbegginers',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='webdesign',
            name='cat',
        ),
        migrations.DeleteModel(
            name='HackerrankProblemSolving',
        ),
        migrations.DeleteModel(
            name='PythonForBegginers',
        ),
        migrations.DeleteModel(
            name='WebDesign',
        ),
    ]
