# Generated by Django 4.0.1 on 2022-02-17 08:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCodes', '0010_codings_remove_pythonforbegginers_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codings',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
