# Generated by Django 4.0.1 on 2022-01-23 05:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBlog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('pub_date', models.DateField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('sub_category', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.CharField(default='Codin India', max_length=150)),
                ('readtime', models.IntegerField()),
            ],
        ),
    ]
