# Generated by Django 4.0.1 on 2022-03-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_user_remove_addblog_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
